# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM oven/bun:alpine

WORKDIR /app

# Copy package files and source code
COPY package.json bun.lockb ./
COPY index.ts ./
COPY tools.ts ./
COPY tsconfig.json ./
COPY utils ./utils

# Install dependencies using bun
RUN bun install --ignore-scripts

CMD ["bun", "run", "index.ts"]
